// Every UN member state plus the Holy See and the State of Palestine (195
// countries total) — the full navigable list for the "Tourist Attractions"
// section. Flag emoji is computed from the ISO 3166-1 alpha-2 code rather
// than hand-typed, so there's no risk of a mismatched flag.
export type Continent = "africa" | "asia" | "europe" | "northAmerica" | "southAmerica" | "oceania";

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  nameAr: string;
  nameEn: string;
  continent: Continent;
}

export function flagEmoji(code: string): string {
  const upper = code.toUpperCase();
  const codePoints = [...upper].map((c) => 0x1f1e6 + (c.charCodeAt(0) - 65));
  return String.fromCodePoint(...codePoints);
}

export const COUNTRIES: Country[] = [
  // Africa
  { code: "DZ", nameAr: "الجزائر", nameEn: "Algeria", continent: "africa" },
  { code: "AO", nameAr: "أنغولا", nameEn: "Angola", continent: "africa" },
  { code: "BJ", nameAr: "بنين", nameEn: "Benin", continent: "africa" },
  { code: "BW", nameAr: "بوتسوانا", nameEn: "Botswana", continent: "africa" },
  { code: "BF", nameAr: "بوركينا فاسو", nameEn: "Burkina Faso", continent: "africa" },
  { code: "BI", nameAr: "بوروندي", nameEn: "Burundi", continent: "africa" },
  { code: "CV", nameAr: "الرأس الأخضر", nameEn: "Cabo Verde", continent: "africa" },
  { code: "CM", nameAr: "الكاميرون", nameEn: "Cameroon", continent: "africa" },
  { code: "CF", nameAr: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic", continent: "africa" },
  { code: "TD", nameAr: "تشاد", nameEn: "Chad", continent: "africa" },
  { code: "KM", nameAr: "جزر القمر", nameEn: "Comoros", continent: "africa" },
  { code: "CG", nameAr: "الكونغو", nameEn: "Republic of the Congo", continent: "africa" },
  { code: "CD", nameAr: "الكونغو الديمقراطية", nameEn: "DR Congo", continent: "africa" },
  { code: "DJ", nameAr: "جيبوتي", nameEn: "Djibouti", continent: "africa" },
  { code: "EG", nameAr: "مصر", nameEn: "Egypt", continent: "africa" },
  { code: "GQ", nameAr: "غينيا الاستوائية", nameEn: "Equatorial Guinea", continent: "africa" },
  { code: "ER", nameAr: "إريتريا", nameEn: "Eritrea", continent: "africa" },
  { code: "SZ", nameAr: "إسواتيني", nameEn: "Eswatini", continent: "africa" },
  { code: "ET", nameAr: "إثيوبيا", nameEn: "Ethiopia", continent: "africa" },
  { code: "GA", nameAr: "الغابون", nameEn: "Gabon", continent: "africa" },
  { code: "GM", nameAr: "غامبيا", nameEn: "Gambia", continent: "africa" },
  { code: "GH", nameAr: "غانا", nameEn: "Ghana", continent: "africa" },
  { code: "GN", nameAr: "غينيا", nameEn: "Guinea", continent: "africa" },
  { code: "GW", nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau", continent: "africa" },
  { code: "CI", nameAr: "ساحل العاج", nameEn: "Côte d'Ivoire", continent: "africa" },
  { code: "KE", nameAr: "كينيا", nameEn: "Kenya", continent: "africa" },
  { code: "LS", nameAr: "ليسوتو", nameEn: "Lesotho", continent: "africa" },
  { code: "LR", nameAr: "ليبيريا", nameEn: "Liberia", continent: "africa" },
  { code: "LY", nameAr: "ليبيا", nameEn: "Libya", continent: "africa" },
  { code: "MG", nameAr: "مدغشقر", nameEn: "Madagascar", continent: "africa" },
  { code: "MW", nameAr: "مالاوي", nameEn: "Malawi", continent: "africa" },
  { code: "ML", nameAr: "مالي", nameEn: "Mali", continent: "africa" },
  { code: "MR", nameAr: "موريتانيا", nameEn: "Mauritania", continent: "africa" },
  { code: "MU", nameAr: "موريشيوس", nameEn: "Mauritius", continent: "africa" },
  { code: "MA", nameAr: "المغرب", nameEn: "Morocco", continent: "africa" },
  { code: "MZ", nameAr: "موزمبيق", nameEn: "Mozambique", continent: "africa" },
  { code: "NA", nameAr: "ناميبيا", nameEn: "Namibia", continent: "africa" },
  { code: "NE", nameAr: "النيجر", nameEn: "Niger", continent: "africa" },
  { code: "NG", nameAr: "نيجيريا", nameEn: "Nigeria", continent: "africa" },
  { code: "RW", nameAr: "رواندا", nameEn: "Rwanda", continent: "africa" },
  { code: "ST", nameAr: "ساو تومي وبرينسيبي", nameEn: "São Tomé and Príncipe", continent: "africa" },
  { code: "SN", nameAr: "السنغال", nameEn: "Senegal", continent: "africa" },
  { code: "SC", nameAr: "سيشل", nameEn: "Seychelles", continent: "africa" },
  { code: "SL", nameAr: "سيراليون", nameEn: "Sierra Leone", continent: "africa" },
  { code: "SO", nameAr: "الصومال", nameEn: "Somalia", continent: "africa" },
  { code: "ZA", nameAr: "جنوب أفريقيا", nameEn: "South Africa", continent: "africa" },
  { code: "SS", nameAr: "جنوب السودان", nameEn: "South Sudan", continent: "africa" },
  { code: "SD", nameAr: "السودان", nameEn: "Sudan", continent: "africa" },
  { code: "TZ", nameAr: "تنزانيا", nameEn: "Tanzania", continent: "africa" },
  { code: "TG", nameAr: "توغو", nameEn: "Togo", continent: "africa" },
  { code: "TN", nameAr: "تونس", nameEn: "Tunisia", continent: "africa" },
  { code: "UG", nameAr: "أوغندا", nameEn: "Uganda", continent: "africa" },
  { code: "ZM", nameAr: "زامبيا", nameEn: "Zambia", continent: "africa" },
  { code: "ZW", nameAr: "زيمبابوي", nameEn: "Zimbabwe", continent: "africa" },

  // Asia (incl. Middle East)
  { code: "AF", nameAr: "أفغانستان", nameEn: "Afghanistan", continent: "asia" },
  { code: "AM", nameAr: "أرمينيا", nameEn: "Armenia", continent: "asia" },
  { code: "AZ", nameAr: "أذربيجان", nameEn: "Azerbaijan", continent: "asia" },
  { code: "BH", nameAr: "البحرين", nameEn: "Bahrain", continent: "asia" },
  { code: "BD", nameAr: "بنغلاديش", nameEn: "Bangladesh", continent: "asia" },
  { code: "BT", nameAr: "بوتان", nameEn: "Bhutan", continent: "asia" },
  { code: "BN", nameAr: "بروناي", nameEn: "Brunei", continent: "asia" },
  { code: "KH", nameAr: "كمبوديا", nameEn: "Cambodia", continent: "asia" },
  { code: "CN", nameAr: "الصين", nameEn: "China", continent: "asia" },
  { code: "GE", nameAr: "جورجيا", nameEn: "Georgia", continent: "asia" },
  { code: "IN", nameAr: "الهند", nameEn: "India", continent: "asia" },
  { code: "ID", nameAr: "إندونيسيا", nameEn: "Indonesia", continent: "asia" },
  { code: "IR", nameAr: "إيران", nameEn: "Iran", continent: "asia" },
  { code: "IQ", nameAr: "العراق", nameEn: "Iraq", continent: "asia" },
  { code: "IL", nameAr: "فلسطين المحتلة", nameEn: "Israel", continent: "asia" },
  { code: "JP", nameAr: "اليابان", nameEn: "Japan", continent: "asia" },
  { code: "JO", nameAr: "الأردن", nameEn: "Jordan", continent: "asia" },
  { code: "KZ", nameAr: "كازاخستان", nameEn: "Kazakhstan", continent: "asia" },
  { code: "KW", nameAr: "الكويت", nameEn: "Kuwait", continent: "asia" },
  { code: "KG", nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan", continent: "asia" },
  { code: "LA", nameAr: "لاوس", nameEn: "Laos", continent: "asia" },
  { code: "LB", nameAr: "لبنان", nameEn: "Lebanon", continent: "asia" },
  { code: "MY", nameAr: "ماليزيا", nameEn: "Malaysia", continent: "asia" },
  { code: "MV", nameAr: "المالديف", nameEn: "Maldives", continent: "asia" },
  { code: "MN", nameAr: "منغوليا", nameEn: "Mongolia", continent: "asia" },
  { code: "MM", nameAr: "ميانمار", nameEn: "Myanmar", continent: "asia" },
  { code: "NP", nameAr: "نيبال", nameEn: "Nepal", continent: "asia" },
  { code: "KP", nameAr: "كوريا الشمالية", nameEn: "North Korea", continent: "asia" },
  { code: "OM", nameAr: "عُمان", nameEn: "Oman", continent: "asia" },
  { code: "PK", nameAr: "باكستان", nameEn: "Pakistan", continent: "asia" },
  { code: "PS", nameAr: "فلسطين", nameEn: "Palestine", continent: "asia" },
  { code: "PH", nameAr: "الفلبين", nameEn: "Philippines", continent: "asia" },
  { code: "QA", nameAr: "قطر", nameEn: "Qatar", continent: "asia" },
  { code: "SA", nameAr: "السعودية", nameEn: "Saudi Arabia", continent: "asia" },
  { code: "SG", nameAr: "سنغافورة", nameEn: "Singapore", continent: "asia" },
  { code: "KR", nameAr: "كوريا الجنوبية", nameEn: "South Korea", continent: "asia" },
  { code: "LK", nameAr: "سريلانكا", nameEn: "Sri Lanka", continent: "asia" },
  { code: "SY", nameAr: "سوريا", nameEn: "Syria", continent: "asia" },
  { code: "TJ", nameAr: "طاجيكستان", nameEn: "Tajikistan", continent: "asia" },
  { code: "TH", nameAr: "تايلاند", nameEn: "Thailand", continent: "asia" },
  { code: "TL", nameAr: "تيمور الشرقية", nameEn: "Timor-Leste", continent: "asia" },
  { code: "TR", nameAr: "تركيا", nameEn: "Turkey", continent: "asia" },
  { code: "TM", nameAr: "تركمانستان", nameEn: "Turkmenistan", continent: "asia" },
  { code: "AE", nameAr: "الإمارات", nameEn: "United Arab Emirates", continent: "asia" },
  { code: "UZ", nameAr: "أوزبكستان", nameEn: "Uzbekistan", continent: "asia" },
  { code: "VN", nameAr: "فيتنام", nameEn: "Vietnam", continent: "asia" },
  { code: "YE", nameAr: "اليمن", nameEn: "Yemen", continent: "asia" },

  // Europe
  { code: "AL", nameAr: "ألبانيا", nameEn: "Albania", continent: "europe" },
  { code: "AD", nameAr: "أندورا", nameEn: "Andorra", continent: "europe" },
  { code: "AT", nameAr: "النمسا", nameEn: "Austria", continent: "europe" },
  { code: "BY", nameAr: "روسيا البيضاء", nameEn: "Belarus", continent: "europe" },
  { code: "BE", nameAr: "بلجيكا", nameEn: "Belgium", continent: "europe" },
  { code: "BA", nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina", continent: "europe" },
  { code: "BG", nameAr: "بلغاريا", nameEn: "Bulgaria", continent: "europe" },
  { code: "HR", nameAr: "كرواتيا", nameEn: "Croatia", continent: "europe" },
  { code: "CY", nameAr: "قبرص", nameEn: "Cyprus", continent: "europe" },
  { code: "CZ", nameAr: "التشيك", nameEn: "Czechia", continent: "europe" },
  { code: "DK", nameAr: "الدنمارك", nameEn: "Denmark", continent: "europe" },
  { code: "EE", nameAr: "إستونيا", nameEn: "Estonia", continent: "europe" },
  { code: "FI", nameAr: "فنلندا", nameEn: "Finland", continent: "europe" },
  { code: "FR", nameAr: "فرنسا", nameEn: "France", continent: "europe" },
  { code: "DE", nameAr: "ألمانيا", nameEn: "Germany", continent: "europe" },
  { code: "GR", nameAr: "اليونان", nameEn: "Greece", continent: "europe" },
  { code: "HU", nameAr: "المجر", nameEn: "Hungary", continent: "europe" },
  { code: "IS", nameAr: "آيسلندا", nameEn: "Iceland", continent: "europe" },
  { code: "IE", nameAr: "أيرلندا", nameEn: "Ireland", continent: "europe" },
  { code: "IT", nameAr: "إيطاليا", nameEn: "Italy", continent: "europe" },
  { code: "LV", nameAr: "لاتفيا", nameEn: "Latvia", continent: "europe" },
  { code: "LI", nameAr: "ليختنشتاين", nameEn: "Liechtenstein", continent: "europe" },
  { code: "LT", nameAr: "ليتوانيا", nameEn: "Lithuania", continent: "europe" },
  { code: "LU", nameAr: "لوكسمبورغ", nameEn: "Luxembourg", continent: "europe" },
  { code: "MT", nameAr: "مالطا", nameEn: "Malta", continent: "europe" },
  { code: "MD", nameAr: "مولدوفا", nameEn: "Moldova", continent: "europe" },
  { code: "MC", nameAr: "موناكو", nameEn: "Monaco", continent: "europe" },
  { code: "ME", nameAr: "الجبل الأسود", nameEn: "Montenegro", continent: "europe" },
  { code: "NL", nameAr: "هولندا", nameEn: "Netherlands", continent: "europe" },
  { code: "MK", nameAr: "مقدونيا الشمالية", nameEn: "North Macedonia", continent: "europe" },
  { code: "NO", nameAr: "النرويج", nameEn: "Norway", continent: "europe" },
  { code: "PL", nameAr: "بولندا", nameEn: "Poland", continent: "europe" },
  { code: "PT", nameAr: "البرتغال", nameEn: "Portugal", continent: "europe" },
  { code: "RO", nameAr: "رومانيا", nameEn: "Romania", continent: "europe" },
  { code: "RU", nameAr: "روسيا", nameEn: "Russia", continent: "europe" },
  { code: "SM", nameAr: "سان مارينو", nameEn: "San Marino", continent: "europe" },
  { code: "RS", nameAr: "صربيا", nameEn: "Serbia", continent: "europe" },
  { code: "SK", nameAr: "سلوفاكيا", nameEn: "Slovakia", continent: "europe" },
  { code: "SI", nameAr: "سلوفينيا", nameEn: "Slovenia", continent: "europe" },
  { code: "ES", nameAr: "إسبانيا", nameEn: "Spain", continent: "europe" },
  { code: "SE", nameAr: "السويد", nameEn: "Sweden", continent: "europe" },
  { code: "CH", nameAr: "سويسرا", nameEn: "Switzerland", continent: "europe" },
  { code: "UA", nameAr: "أوكرانيا", nameEn: "Ukraine", continent: "europe" },
  { code: "GB", nameAr: "بريطانيا", nameEn: "United Kingdom", continent: "europe" },
  { code: "VA", nameAr: "الفاتيكان", nameEn: "Vatican City", continent: "europe" },

  // North America
  { code: "AG", nameAr: "أنتيغوا وباربودا", nameEn: "Antigua and Barbuda", continent: "northAmerica" },
  { code: "BS", nameAr: "باهاماس", nameEn: "Bahamas", continent: "northAmerica" },
  { code: "BB", nameAr: "باربادوس", nameEn: "Barbados", continent: "northAmerica" },
  { code: "BZ", nameAr: "بليز", nameEn: "Belize", continent: "northAmerica" },
  { code: "CA", nameAr: "كندا", nameEn: "Canada", continent: "northAmerica" },
  { code: "CR", nameAr: "كوستاريكا", nameEn: "Costa Rica", continent: "northAmerica" },
  { code: "CU", nameAr: "كوبا", nameEn: "Cuba", continent: "northAmerica" },
  { code: "DM", nameAr: "دومينيكا", nameEn: "Dominica", continent: "northAmerica" },
  { code: "DO", nameAr: "جمهورية الدومينيكان", nameEn: "Dominican Republic", continent: "northAmerica" },
  { code: "SV", nameAr: "السلفادور", nameEn: "El Salvador", continent: "northAmerica" },
  { code: "GD", nameAr: "غرينادا", nameEn: "Grenada", continent: "northAmerica" },
  { code: "GT", nameAr: "غواتيمالا", nameEn: "Guatemala", continent: "northAmerica" },
  { code: "HT", nameAr: "هايتي", nameEn: "Haiti", continent: "northAmerica" },
  { code: "HN", nameAr: "هندوراس", nameEn: "Honduras", continent: "northAmerica" },
  { code: "JM", nameAr: "جامايكا", nameEn: "Jamaica", continent: "northAmerica" },
  { code: "MX", nameAr: "المكسيك", nameEn: "Mexico", continent: "northAmerica" },
  { code: "NI", nameAr: "نيكاراغوا", nameEn: "Nicaragua", continent: "northAmerica" },
  { code: "PA", nameAr: "بنما", nameEn: "Panama", continent: "northAmerica" },
  { code: "KN", nameAr: "سانت كيتس ونيفس", nameEn: "Saint Kitts and Nevis", continent: "northAmerica" },
  { code: "LC", nameAr: "سانت لوسيا", nameEn: "Saint Lucia", continent: "northAmerica" },
  { code: "VC", nameAr: "سانت فينسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines", continent: "northAmerica" },
  { code: "TT", nameAr: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago", continent: "northAmerica" },
  { code: "US", nameAr: "الولايات المتحدة", nameEn: "United States", continent: "northAmerica" },

  // South America
  { code: "AR", nameAr: "الأرجنتين", nameEn: "Argentina", continent: "southAmerica" },
  { code: "BO", nameAr: "بوليفيا", nameEn: "Bolivia", continent: "southAmerica" },
  { code: "BR", nameAr: "البرازيل", nameEn: "Brazil", continent: "southAmerica" },
  { code: "CL", nameAr: "تشيلي", nameEn: "Chile", continent: "southAmerica" },
  { code: "CO", nameAr: "كولومبيا", nameEn: "Colombia", continent: "southAmerica" },
  { code: "EC", nameAr: "الإكوادور", nameEn: "Ecuador", continent: "southAmerica" },
  { code: "GY", nameAr: "غيانا", nameEn: "Guyana", continent: "southAmerica" },
  { code: "PY", nameAr: "باراغواي", nameEn: "Paraguay", continent: "southAmerica" },
  { code: "PE", nameAr: "بيرو", nameEn: "Peru", continent: "southAmerica" },
  { code: "SR", nameAr: "سورينام", nameEn: "Suriname", continent: "southAmerica" },
  { code: "UY", nameAr: "الأوروغواي", nameEn: "Uruguay", continent: "southAmerica" },
  { code: "VE", nameAr: "فنزويلا", nameEn: "Venezuela", continent: "southAmerica" },

  // Oceania
  { code: "AU", nameAr: "أستراليا", nameEn: "Australia", continent: "oceania" },
  { code: "FJ", nameAr: "فيجي", nameEn: "Fiji", continent: "oceania" },
  { code: "KI", nameAr: "كيريباتي", nameEn: "Kiribati", continent: "oceania" },
  { code: "MH", nameAr: "جزر مارشال", nameEn: "Marshall Islands", continent: "oceania" },
  { code: "FM", nameAr: "ميكرونيزيا", nameEn: "Micronesia", continent: "oceania" },
  { code: "NR", nameAr: "ناورو", nameEn: "Nauru", continent: "oceania" },
  { code: "NZ", nameAr: "نيوزيلندا", nameEn: "New Zealand", continent: "oceania" },
  { code: "PW", nameAr: "بالاو", nameEn: "Palau", continent: "oceania" },
  { code: "PG", nameAr: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea", continent: "oceania" },
  { code: "WS", nameAr: "ساموا", nameEn: "Samoa", continent: "oceania" },
  { code: "SB", nameAr: "جزر سليمان", nameEn: "Solomon Islands", continent: "oceania" },
  { code: "TO", nameAr: "تونغا", nameEn: "Tonga", continent: "oceania" },
  { code: "TV", nameAr: "توفالو", nameEn: "Tuvalu", continent: "oceania" },
  { code: "VU", nameAr: "فانواتو", nameEn: "Vanuatu", continent: "oceania" },
];

export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}
